output "ami_info" {
    value = data.aws_ami.latest_amazon_linux
    description = "The AMI data used for instances"
}

output "message" {
    value = var.x
}

output "vpc_id" {
    value       = data.aws_vpcs.default_vpc.ids[0]
    description = "Default VPC id"
}

output "instance_public_ips" {
    value       = aws_instance.web[*].public_ip
    description = "Public IPs of created instances"
}

output "ansible_inventory" {
    value       = fileexists("${path.module}/inventory") ? file("${path.module}/inventory") : ""
    description = "Inventory content generated by terraform (if present)"
}