- name: For K8s Master Node Configuration Only
  hosts: k8s-master
  become: true
  tasks:
    - name: Check if Kubernetes is already initialized
      command: kubectl cluster-info
      register: kubectl_status
      ignore_errors: yes

    - name: Define the Master Node Private IP
      shell: ip addr show eth0 | awk '/inet / {print $2}' | cut -d/ -f1
      register: master_private_ip
      when: kubectl_status.failed

    - name: Define the POD_CIDR variable
      set_fact:
        pod_cidr: "192.168.0.0/16"
      when: kubectl_status.failed

    - name: Define the Master Node name in short
      shell: hostname -s
      register: nodename
      when: kubectl_status.failed

    - name: Initialize the Kubernetes Cluster
      shell: |
        kubeadm init --apiserver-advertise-address="{{ master_private_ip.stdout }}" \
        --apiserver-cert-extra-sans="{{ master_private_ip.stdout }}" \
        --pod-network-cidr="192.168.0.0/16" \
        --node-name="{{ nodename.stdout }}" \
        --ignore-preflight-errors Swap
      register: kubeinit_details
      when: kubectl_status.failed

    - name: Display Kubeadm init output
      debug:
        var: kubeinit_details
      when: kubectl_status.failed

    # Further tasks...


    - name: Create .kube directory if it doesn't exist
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
      when: kubectl_status.failed

    - name: Copy admin.conf to user's .kube directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        remote_src: yes
        mode: '0644'
      when: kubectl_status.failed

    - name: Change ownership of .kube/config to the user
      file:
        path: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
      when: kubectl_status.failed

    - name: Configure the CNI using Calico
      shell:
        cmd: kubectl apply -f https://raw.githubusercontent.com/sudhanshuvlog/kubernetes-multinode-cluster-ansible-aws/main/calico.yaml
      when: kubectl_status.failed

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command
      when: kubectl_status.failed

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
      when: kubectl_status.failed

- name: In the worker Node
  hosts: k8s-workers
  become: true
  tasks:
    - name: Check if kubelet is running
      shell: |
        systemctl is-active --quiet kubelet
      register: kubelet_status
      ignore_errors: yes

    - name: Debug kubelet status
      debug:
        msg: "Kubelet is {{ 'running' if kubelet_status.rc == 0 else 'not running' }}."

    - name: Set fact to determine if node is in the cluster
      set_fact:
        node_in_cluster: "{{ kubelet_status.rc == 0 }}"
    
    - name: Copy the join command to server location
      copy:
        src: join-command
        dest: /tmp/join-command.sh
        mode: '0777'
      when: not node_in_cluster

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh
      when: not node_in_cluster
